-- ============================================================
-- BCSO TEU ACTIVITY TRACKER - COMPLETE SUPABASE DATABASE
-- Run this entire file in Supabase -> SQL Editor.
-- ============================================================

create table if not exists public.teu_events (
    id bigint generated by default as identity primary key,
    category text not null check (
        category in (
            'arrest',
            'pit',
            'pursuit',
            'citation',
            'crash',
            'grappler',
            'felony_stop',
            'assist',
            'dui',
            'other'
        )
    ),
    member text,
    activity_date date not null,
    month_start date not null,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists teu_events_month_idx
on public.teu_events(month_start, created_at desc);

create index if not exists teu_events_category_idx
on public.teu_events(category);

create index if not exists teu_events_member_idx
on public.teu_events(member);

create table if not exists public.teu_admins (
    user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.teu_events enable row level security;
alter table public.teu_admins enable row level security;

drop policy if exists "TEU public read" on public.teu_events;
create policy "TEU public read"
on public.teu_events
for select
to anon, authenticated
using (true);

drop policy if exists "TEU public insert" on public.teu_events;
create policy "TEU public insert"
on public.teu_events
for insert
to anon, authenticated
with check (
    month_start = date_trunc('month', activity_date)::date
);

drop policy if exists "Admins can read own admin record" on public.teu_admins;
create policy "Admins can read own admin record"
on public.teu_admins
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.reset_current_teu_month(target_month date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    deleted_count integer;
begin
    if not exists (
        select 1
        from public.teu_admins
        where user_id = auth.uid()
    ) then
        raise exception 'Not authorized';
    end if;

    delete from public.teu_events
    where month_start = date_trunc('month', target_month)::date;

    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;

revoke all on function public.reset_current_teu_month(date) from public;
grant execute on function public.reset_current_teu_month(date) to authenticated;

do $$
begin
    alter publication supabase_realtime add table public.teu_events;
exception
    when duplicate_object then null;
end $$;

-- ============================================================
-- AFTER YOU CREATE THE ADMIN USER IN SUPABASE AUTHENTICATION:
--
-- 1. Go to Authentication -> Users.
-- 2. Create:
--      Email: lc0628339@gmail.com
--      Password: zeAdrHgpnH1@
-- 3. Copy the user's UUID.
-- 4. Run:
--
-- insert into public.teu_admins (user_id)
-- values ('PASTE-ADMIN-USER-UUID-HERE');
--
-- The reset function will then enforce admin authorization
-- at the database level.
-- ============================================================

-- ============================================================
-- TEU ROSTER
-- Run this section in Supabase SQL Editor to add the roster
-- to an existing tracker database.
-- ============================================================

create table if not exists public.teu_roster (
    id bigint generated by default as identity primary key,
    callsign text not null,
    name text not null,
    rank text not null,
    subdivision_rank text not null check (
        subdivision_rank in (
            'TEU Traffic Member',
            'FTO',
            'Co Commander',
            'Commander'
        )
    ),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists teu_roster_active_idx
on public.teu_roster(active, callsign);

alter table public.teu_roster enable row level security;

drop policy if exists "TEU roster public read" on public.teu_roster;
create policy "TEU roster public read"
on public.teu_roster for select
to anon, authenticated
using (true);

drop policy if exists "TEU admins can insert roster" on public.teu_roster;
create policy "TEU admins can insert roster"
on public.teu_roster for insert
to authenticated
with check (exists (
    select 1 from public.teu_admins where user_id = auth.uid()
));

drop policy if exists "TEU admins can update roster" on public.teu_roster;
create policy "TEU admins can update roster"
on public.teu_roster for update
to authenticated
using (exists (
    select 1 from public.teu_admins where user_id = auth.uid()
))
with check (exists (
    select 1 from public.teu_admins where user_id = auth.uid()
));

drop policy if exists "TEU admins can delete roster" on public.teu_roster;
create policy "TEU admins can delete roster"
on public.teu_roster for delete
to authenticated
using (exists (
    select 1 from public.teu_admins where user_id = auth.uid()
));

create or replace function public.update_teu_roster_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists teu_roster_updated_at on public.teu_roster;
create trigger teu_roster_updated_at
before update on public.teu_roster
for each row execute function public.update_teu_roster_timestamp();

do $$
begin
  alter publication supabase_realtime add table public.teu_roster;
exception when duplicate_object then null;
end $$;
